encryptionsalt: v1:++R8yIB0haQ=:v1:AlSkl9UMXWY+M0sv:uBDOKNwxu99nkvBKuG3equaJWhVohw==
config:
  gcp:project:
    secure: v1:IlCit8HReewyjabA:4uZLzFKepZkxCIKZoMUgPJbSVLGHN3EJzzo3zDa7OaM=
  gcp:region: asia-northeast1
  exvs-analyzer:artifactRegistryRepo:
    secure: v1:LKL/uLaI0M1QXk23:XzHVMNggv2nmPiflcGDwm7eOG72fWwWm7TXfhiFT3wwkA6ffT8Pl
  exvs-analyzer:gcsBucket:
    secure: v1:TDDa4uPP6WTJLtpB:xqFio46JV2yiJsBGGsGKSJEFKe//UOF+gnQuRr42vCoy5PWlmw==
  exvs-analyzer:billingAccount:
    secure: v1:1dC4a6U72QN65TT7:Hy7Q7sGtndWouWFI6kWmYjL2MuH6uGRfMNcpt8BzLr7++Ybi
  exvs-analyzer:budgetAmount:
    secure: v1:t/btXxy5q94Z048L:UYbSe5mE/EkbOjVkfKLyvFGYbq0=
  exvs-analyzer:image:
    secure: v1:M0xwOizR13d1hFXd:NNKu4x2RQ5y20QPaE9b+/zhsh4MWfRFdWzTCQz6erSt0wboyLy8TT44PsFxNJM0q7vLeJ18=
  exvs-analyzer:domain: www.exvs-analyzer.com
  exvs-analyzer:domainVerificationTxt: google-site-verification=TAXKxm2PncupGRZkk0mBxIxslp_7aZj-w9dxPAi-ObE
  exvs-analyzer:pulumiStateBucket:
    secure: v1:DTT5hikna9CWd6by:Nx5wUNbRTnn7SC03sCc5yPzugTPiZSwmiwJ0vjNRrsparkbP48cmYa5OJAFp
  exvs-analyzer:githubRepo: yuki9431/exvs-analyzer
  exvs-analyzer:computeSa:
    secure: v1:IgRCxU3FUKAgYFVM:84Vd9wpKbv4aii4ZiSsWCwdpXAEfNtx6l52NGnLzp6b2YZL/t04CeFNJTHSmsEOqGxHRazl1yAnoAUhe0ZfJKWRO
  exvs-analyzer:ownerEmail:
    secure: v1:PPXFgxigyRzBi94p:D9+0MQOCQGmsIsLGmPxFp8LzFnsuwRqgS+2HkAMWIXJR8FkJ
