encryptionsalt: v1:evUdMCCS5y8=:v1:/OISA4XjAeNSfiWM:dpR57gY0VOZJwLVX4naIh01vl/GXDg==
config:
  gcp:project:
    secure: v1:GFZ/rFuC+i0R/bSv:NNxS64NTcMbplD9tvMzrMcd5mprAYX+Q5EByqXsk5dE=
  gcp:region: asia-northeast1
  exvs-app:cpu: "1"
  exvs-app:memory: 512Mi
  exvs-app:maxInstances: "1"
  exvs-app:domain: stg.exvs-analyzer.com
  exvs-app:image:
    secure: v1:pXokt6CwVuPeZ3w7:oZlGtkLXeIzMmvgHvR50VmUBTOrhgBGUjig2XCmBQr/1TijDwaoag9tT9V6BYMa2DzYlbr+e+A4Pt+koDtQezQu7zsdUA8xbfAjgJ+lRwSBpy9ReVgk/bmSv2bDbMUx63TpauhYYnuUX6jUX20i+8RnUWQfOVgutzC5QbtKbuYLIdWXg9pSP2jM7J7cAPA==
  exvs-app:gcsBucket:
    secure: v1:ZpepUFqv5KJMeSu1:0iAEyxxqllexQbeTezIhRPKvwR+2/sW5VY9iqpRWtWDeidp+gw==
  exvs-app:sharedStack: organization/exvs-shared/shared
  exvs-app:serviceName: stg-exvs-analyzer
