config:
  gcp:project:
    secure: v1:PLACEHOLDER:needs-pulumi-config-set
  gcp:region: asia-northeast1
  exvs-app:cpu: "2"
  exvs-app:memory: "1Gi"
  exvs-app:maxInstances: "3"
  exvs-app:domain: www.exvs-analyzer.com
  exvs-app:gcsBucket:
    secure: v1:PLACEHOLDER:needs-pulumi-config-set
  exvs-app:image:
    secure: v1:PLACEHOLDER:needs-pulumi-config-set
  exvs-app:sharedStack: exvs-shared/dev
