encryptionsalt: v1:evUdMCCS5y8=:v1:/OISA4XjAeNSfiWM:dpR57gY0VOZJwLVX4naIh01vl/GXDg==
config:
  gcp:project:
    secure: v1:GFZ/rFuC+i0R/bSv:NNxS64NTcMbplD9tvMzrMcd5mprAYX+Q5EByqXsk5dE=
  gcp:region: asia-northeast1
  exvs-app:cpu: "1"
  exvs-app:memory: 512Mi
  exvs-app:maxInstances: "1"
  exvs-app:domain: stg.exvs-analyzer.com
  exvs-app:image:
    secure: v1:C3OuUeJFj+jOOlkE:/qmw2KNyqmF5Ascqu2W3RxPljFdadtLzmmNhLaj96XZIW09O1TDAyyB4dQIJ7Bry9VqopGaCcds5c+Y0qYFG9rOAYReGa/wLHdz8F6xj17ASA/EbgSlqzm+pqUppAA7hwLo4BZprfnZ1NIkHVjtiWNIY5MoGYTFW1/Ww0CR7tgSANCL2mU9MBV6wEIWX7g==
  exvs-app:gcsBucket:
    secure: v1:ZpepUFqv5KJMeSu1:0iAEyxxqllexQbeTezIhRPKvwR+2/sW5VY9iqpRWtWDeidp+gw==
  exvs-app:sharedStack: organization/exvs-shared/shared
  exvs-app:serviceName: stg-exvs-analyzer
