encryptionsalt: v1:evUdMCCS5y8=:v1:/OISA4XjAeNSfiWM:dpR57gY0VOZJwLVX4naIh01vl/GXDg==
config:
  gcp:project:
    secure: v1:GFZ/rFuC+i0R/bSv:NNxS64NTcMbplD9tvMzrMcd5mprAYX+Q5EByqXsk5dE=
  gcp:region: asia-northeast1
  exvs-app:cpu: "1"
  exvs-app:memory: 512Mi
  exvs-app:maxInstances: "1"
  exvs-app:domain: stg.exvs-analyzer.com
  exvs-app:image:
    secure: v1:bD+HQeGo/4b/wr/l:XK/7y1Ji/bj2C+xRlUyTHHHNxNCVWLdDTZOzDlq9Oiwk0MjMYIYVKBQDA/ehyXKTTV37aECDP/TaZhLmylfRWUhpBbL0GWrWgl8/n5OdoanRY0mfKcaTqWKaHmQv7O6kVwJFCsSg4NFuAGUg5L/QCSxK7c2DUNCcrjl1PMX+TYBNX9On5bHDfWzhoMMn0g==
  exvs-app:gcsBucket:
    secure: v1:ZpepUFqv5KJMeSu1:0iAEyxxqllexQbeTezIhRPKvwR+2/sW5VY9iqpRWtWDeidp+gw==
  exvs-app:sharedStack: organization/exvs-shared/shared
  exvs-app:serviceName: stg-exvs-analyzer
