config:
  gcp:project:
    secure: v1:ZNRhblgzjExwl3oi:jCZSB3rnlQbA4BQScwj+0FLexKyrfkNErex5lkvAkYk=
  gcp:region: asia-northeast1
  exvs-app:serviceName: exvs-analyzer
  exvs-app:cpu: "2"
  exvs-app:memory: "1Gi"
  exvs-app:maxInstances: "3"
  exvs-app:domain: www.exvs-analyzer.com
  exvs-app:gcsBucket:
    secure: v1:/zqLjVBPrsfEzVcl:NiJy0Q5GyfXBNnaUDXoVF49BCgQK/tIF2No0PMCrMOy2ousY2A==
  exvs-app:image:
    secure: v1:mhPBarrPRKwxwN/V:yInDQJcQxi7rfKXeyF1qfpdNObmXiWQhMXO7ICXmc8y61DcQ3aZBwhjBoqL3fQju1KqR8vEOhYfLoXe6ECPryA+iRVVwMiW96TdQf9He8fGS6dQbJeeNwTr4QkzjuQvGcpc9zwLtlboYHIB9pPczx6q42SzPH4fNzudyuO2QpzUX79zl7aEbCtVc5/P28g==
  exvs-app:sharedStack: organization/exvs-shared/shared
encryptionsalt: v1:ToX9TGUsy/w=:v1:i/etZsivSPrFlstj:Ext0d7LnzlUd5QqVkA9H3ECUQuMZzQ==
